# Generated by Django 5.2 on 2025-04-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_vote_timestamp_alter_vote_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
